import React, { createContext, useContext, useState } from "react";

export type LangCode = "en" | "fr" | "es" | "ar" | "zh";
const LANG_KEY = "gkc_lang";

export interface T {
  nav: {
    home: string; inventory: string; services: string; about: string;
    contact: string; viewCatalog: string; language: string;
  };
  hero: {
    badge: string; line1: string; line2: string; line3: string; line4: string;
    sub: string; cta1: string; cta2: string;
  };
  stats: { units: string; trucks: string; mining: string; drilling: string; };
  featured: { label: string; heading: string; sub: string; viewAll: string; empty: string; error: string; };
  categories: {
    heading: string; sub: string;
    trucks: string; trucksDesc: string;
    mining: string; miningDesc: string;
    drilling: string; drillingDesc: string;
    browse: string;
  };
  why: {
    heading1: string; heading2: string; sub: string;
    v1: string; v1d: string; v2: string; v2d: string;
    v3: string; v3d: string; v4: string; v4d: string;
  };
  cta: { heading: string; sub: string; btn1: string; btn2: string; };
  products: {
    pageTitle: string; pageSub: string;
    all: string; trucks: string; mining: string; drilling: string;
    inStock: string; search: string;
    sortName: string; sortAsc: string; sortDesc: string;
    showing: string; results: string;
    noResults: string; noResultsDesc: string; reset: string;
    error: string; errorDesc: string; retry: string;
  };
  about: {
    tagline: string; title1: string; title2: string; sub: string;
    missionTitle: string; missionText: string;
    visionTitle: string; visionText: string;
    yearsExp: string; unitsDelivered: string;
    valuesLabel: string; valuesTitle: string;
    val1: string; val1d: string;
    val2: string; val2d: string;
    val3: string; val3d: string;
    driveTitle: string; driveText: string;
  };
  services: {
    tagline: string; title1: string; title2: string;
    s1: string; s1d: string; s2: string; s2d: string;
    s3: string; s3d: string; s4: string; s4d: string;
    s5: string; s5d: string; s6: string; s6d: string;
    ctaTitle: string; ctaText: string; ctaBtn: string;
  };
  contact: {
    tagline: string; title1: string; title2: string;
    hqTitle: string;
    locLabel: string; locVal: string;
    callLabel: string; emailLabel: string;
    hoursLabel: string; hoursVal: string;
    urgentTitle: string; urgentText: string; urgentLink: string;
    formTitle: string;
    nameLbl: string; emailLbl: string; phoneLbl: string; subjectLbl: string; msgLbl: string;
    opt1: string; opt2: string; opt3: string; opt4: string;
    sendBtn: string; sending: string;
    successTitle: string; successText: string; errorText: string;
  };
  footer: {
    tagline: string; navTitle: string; navHome: string; navInventory: string;
    navServices: string; navAbout: string; navContact: string;
    equipTitle: string; equipTrucks: string; equipMining: string;
    equipDrilling: string; equipFeatured: string;
    hqTitle: string; privacy: string; terms: string;
  };
  common: { inStock: string; outOfStock: string; featured: string; new_: string; used: string; refurbished: string; };
}

const en: T = {
  nav: { home: "Home", inventory: "Inventory", services: "Services", about: "About Us", contact: "Contact", viewCatalog: "View Catalog", language: "Language" },
  hero: { badge: "Garkuwan Kanam & Co Ventures", line1: "Built for", line2: "Scale.", line3: "Driven by", line4: "Power.", sub: "Nigeria's premier gateway to world-class heavy machinery. From deep-well drilling to large-scale mining operations, we deliver the force that builds nations.", cta1: "Explore Inventory", cta2: "Chat with Sales" },
  stats: { units: "Units in Stock", trucks: "Heavy Trucks", mining: "Mining Units", drilling: "Drilling Systems" },
  featured: { label: "Curated Selection", heading: "Featured Stock", sub: "Premium machinery, inspected and ready for immediate deployment to your site.", viewAll: "Full Inventory", empty: "No featured items right now. Browse our full catalog.", error: "Could not load featured products. Please try again." },
  categories: { heading: "Browse by Category", sub: "Find the right equipment for your operation", trucks: "Heavy Trucks", trucksDesc: "Long-haul cargo, tippers & tractor units for road transport", mining: "Mining Trucks", miningDesc: "Giant-scale haul trucks & crawler dozers for mining operations", drilling: "Drilling Motors", drillingDesc: "Downhole mud motors & directional drilling systems", browse: "Browse All" },
  why: { heading1: "The Trusted", heading2: "Industrial Partner", sub: "Garkuwan Kanam & Co Ventures isn't just a supplier. We are an industrial force providing verified, heavy-duty machinery for the most demanding environments on the continent.", v1: "Verified Stock", v1d: "Every unit undergoes a 150-point industrial inspection before listing.", v2: "High Efficiency", v2d: "Optimized machinery for maximum uptime and output.", v3: "Certified Brands", v3d: "Direct partnerships with Caterpillar, FAW, and Mercedes-Benz.", v4: "Regional Reach", v4d: "Full logistics support across all 36 states in Nigeria and beyond." },
  cta: { heading: "Ready to Power Your Operation?", sub: "Consult with our industrial experts today. We provide full technical documentation and logistical support for every acquisition.", btn1: "WhatsApp Sales", btn2: "Request a Quote" },
  products: { pageTitle: "Industrial Catalog", pageSub: "Every unit is industry-certified and field-ready. Filter by category or search specific models.", all: "All Equipment", trucks: "Trucks", mining: "Mining Trucks", drilling: "Drilling Motors", inStock: "In Stock Only", search: "Search models...", sortName: "Sort: Name", sortAsc: "Price: Low–High", sortDesc: "Price: High–Low", showing: "Showing", results: "results", noResults: "No Equipment Matches", noResultsDesc: "Try adjusting your filters or search terms.", reset: "Reset Filters", error: "Failed to Load Inventory", errorDesc: "We couldn't fetch the equipment list. Please check your connection.", retry: "Retry" },
  about: { tagline: "Our Legacy", title1: "Industrial", title2: "Excellence.", sub: "Garkuwan Kanam & Co Ventures stands as a pillar of reliability in Nigeria's heavy equipment sector, bridging the gap between global engineering and local industrial demand.", missionTitle: "Our Mission", missionText: "To empower Nigeria's industrial landscape by providing access to high-performance, verified heavy machinery that drives economic growth and infrastructural development across West Africa.", visionTitle: "Our Vision", visionText: "To be the undisputed first choice for heavy equipment acquisition in West Africa, recognized for uncompromising standards of quality, professional integrity, and technical expertise.", yearsExp: "Years Experience", unitsDelivered: "Units Delivered", valuesLabel: "How We Work", valuesTitle: "Our Core Values", val1: "Integrity", val1d: "Transparency in every transaction. Full history and verification for every piece of equipment we sell.", val2: "Quality", val2d: "We stock only industry-leading brands proven for durability in the harshest industrial environments.", val3: "Partnership", val3d: "Our relationship doesn't end at delivery. We provide ongoing technical support to keep you operational.", driveTitle: "Driving the Future of Nigerian Industry.", driveText: "From the oil fields of the Delta to the mining sites of the North, our equipment is the backbone of Nigerian industry. We are the silent force behind the country's most significant infrastructure projects." },
  services: { tagline: "Industrial Support", title1: "Maintenance", title2: "& Support.", s1: "Preventive Maintenance", s1d: "Scheduled servicing to ensure your heavy machinery operates at peak performance and avoids costly downtime.", s2: "Genuine Spare Parts", s2d: "Comprehensive inventory of authentic OEM parts for Caterpillar, FAW, Mercedes-Benz, and Iveco equipment.", s3: "On-Site Repairs", s3d: "Our mobile technical team deploys directly to your site for immediate mechanical and electrical repairs.", s4: "Fleet Management", s4d: "Comprehensive tracking and optimization services for large-scale industrial fleets across all 36 Nigerian states.", s5: "Technical Certification", s5d: "Official inspection and certification to ensure your equipment meets all Nigerian industrial regulatory standards.", s6: "24/7 Field Support", s6d: "Round-the-clock technical assistance for critical operations in mining, drilling, and construction sectors.", ctaTitle: "Need Immediate Support?", ctaText: "Our technical response team is standing by to assist with your machinery needs across all 36 states in Nigeria.", ctaBtn: "Contact Technical Team" },
  contact: { tagline: "Get in Touch", title1: "Connect with", title2: "Our Experts.", hqTitle: "Headquarters", locLabel: "Location", locVal: "Garkuwan Kanam Industrial Complex,\nVictoria Island, Lagos,\nFederal Republic of Nigeria", callLabel: "Call Us", emailLabel: "Email", hoursLabel: "Business Hours", hoursVal: "Mon–Fri: 08:00 – 18:00\nSaturday: 09:00 – 14:00", urgentTitle: "Urgent Inquiry?", urgentText: "Our procurement specialists are available for immediate consultation on large-scale fleet acquisitions.", urgentLink: "Chat with Sales", formTitle: "Send a Message", nameLbl: "Full Name", emailLbl: "Email Address", phoneLbl: "Phone Number", subjectLbl: "Subject", msgLbl: "Message", opt1: "Equipment Inquiry", opt2: "Technical Support", opt3: "Logistics & Delivery", opt4: "Partnership", sendBtn: "Send Message", sending: "Sending...", successTitle: "Message Sent!", successText: "Thank you for reaching out. Our team will respond within 24 business hours.", errorText: "Failed to send message. Please try again or contact us directly via WhatsApp." },
  footer: { tagline: "Nigeria's premier force in heavy machinery and industrial equipment. Bridging global engineering excellence and local industrial needs.", navTitle: "Navigation", navHome: "Home", navInventory: "Inventory Catalog", navServices: "Maintenance & Parts", navAbout: "Company Profile", navContact: "Get in Touch", equipTitle: "Equipment", equipTrucks: "Heavy Trucks", equipMining: "Mining Solutions", equipDrilling: "Drilling Systems", equipFeatured: "Featured Stock", hqTitle: "Headquarters", privacy: "Privacy Policy", terms: "Terms of Service" },
  common: { inStock: "In Stock", outOfStock: "Out of Stock", featured: "Featured", new_: "New", used: "Used", refurbished: "Refurbished" },
};

const fr: T = {
  nav: { home: "Accueil", inventory: "Inventaire", services: "Services", about: "À Propos", contact: "Contact", viewCatalog: "Voir le Catalogue", language: "Langue" },
  hero: { badge: "Garkuwan Kanam & Co Ventures", line1: "Construit pour", line2: "L'Échelle.", line3: "Propulsé par", line4: "La Puissance.", sub: "La principale passerelle du Nigeria vers les machines lourdes de classe mondiale. Du forage en profondeur aux grandes opérations minières, nous livrons la force qui bâtit les nations.", cta1: "Voir l'Inventaire", cta2: "Contacter les Ventes" },
  stats: { units: "Unités en Stock", trucks: "Camions Lourds", mining: "Unités Minières", drilling: "Systèmes de Forage" },
  featured: { label: "Sélection Curatée", heading: "Stock en Vedette", sub: "Machines de qualité, inspectées et prêtes pour un déploiement immédiat.", viewAll: "Inventaire Complet", empty: "Aucun article en vedette. Parcourez notre catalogue complet.", error: "Impossible de charger les produits en vedette. Veuillez réessayer." },
  categories: { heading: "Parcourir par Catégorie", sub: "Trouvez l'équipement adapté à votre opération", trucks: "Camions Lourds", trucksDesc: "Transport longue distance, bennes & tracteurs routiers", mining: "Camions Miniers", miningDesc: "Camions de transport géants & bouteurs à chenilles", drilling: "Moteurs de Forage", drillingDesc: "Moteurs de fond de trou & forage directionnel", browse: "Tout Parcourir" },
  why: { heading1: "Le Partenaire", heading2: "Industriel de Confiance", sub: "Garkuwan Kanam & Co Ventures n'est pas qu'un fournisseur. Nous sommes une force industrielle fournissant des machines lourdes vérifiées pour les environnements les plus exigeants du continent.", v1: "Stock Vérifié", v1d: "Chaque unité subit une inspection industrielle de 150 points avant inscription.", v2: "Haute Efficacité", v2d: "Machines optimisées pour un temps de fonctionnement et une production maximaux.", v3: "Marques Certifiées", v3d: "Partenariats directs avec Caterpillar, FAW et Mercedes-Benz.", v4: "Portée Régionale", v4d: "Soutien logistique complet dans les 36 États du Nigeria et au-delà." },
  cta: { heading: "Prêt à Propulser Votre Opération?", sub: "Consultez nos experts industriels dès aujourd'hui. Documentation technique complète pour chaque acquisition.", btn1: "WhatsApp Ventes", btn2: "Demander un Devis" },
  products: { pageTitle: "Catalogue Industriel", pageSub: "Chaque unité est certifiée et prête pour le terrain. Filtrez par catégorie ou recherchez des modèles.", all: "Tout l'Équipement", trucks: "Camions", mining: "Camions Miniers", drilling: "Moteurs de Forage", inStock: "En Stock Seulement", search: "Rechercher modèles...", sortName: "Trier: Nom", sortAsc: "Prix: Croissant", sortDesc: "Prix: Décroissant", showing: "Affichage de", results: "résultats", noResults: "Aucun Équipement Trouvé", noResultsDesc: "Essayez d'ajuster vos filtres ou termes de recherche.", reset: "Réinitialiser", error: "Échec du Chargement", errorDesc: "Impossible de récupérer la liste. Vérifiez votre connexion.", retry: "Réessayer" },
  about: { tagline: "Notre Héritage", title1: "Excellence", title2: "Industrielle.", sub: "Garkuwan Kanam & Co Ventures est un pilier de fiabilité dans le secteur des équipements lourds du Nigeria, comblant le fossé entre l'ingénierie mondiale et la demande industrielle locale.", missionTitle: "Notre Mission", missionText: "Autonomiser le paysage industriel du Nigeria en fournissant des machines lourdes vérifiées et hautes performances qui stimulent la croissance économique et le développement infrastructurel.", visionTitle: "Notre Vision", visionText: "Être le premier choix incontesté pour l'acquisition d'équipements lourds en Afrique de l'Ouest, reconnu pour des standards inébranlables de qualité et d'expertise technique.", yearsExp: "Années d'Expérience", unitsDelivered: "Unités Livrées", valuesLabel: "Notre Approche", valuesTitle: "Nos Valeurs Fondamentales", val1: "Intégrité", val1d: "Transparence dans chaque transaction. Historique complet et vérification pour chaque équipement.", val2: "Qualité", val2d: "Nous ne stockons que des marques leaders connues pour leur durabilité dans les environnements industriels.", val3: "Partenariat", val3d: "Notre relation ne s'arrête pas à la livraison. Nous fournissons un support continu pour maintenir vos opérations.", driveTitle: "Moteur de l'Industrie Nigériane.", driveText: "Des champs pétroliers du Delta aux sites miniers du Nord, notre équipement est l'épine dorsale de l'industrie nigériane." },
  services: { tagline: "Support Industriel", title1: "Maintenance", title2: "& Support.", s1: "Maintenance Préventive", s1d: "Entretien programmé pour assurer que vos machines lourdes fonctionnent à des performances optimales.", s2: "Pièces Détachées Authentiques", s2d: "Inventaire complet de pièces OEM authentiques pour Caterpillar, FAW, Mercedes-Benz et Iveco.", s3: "Réparations Sur Site", s3d: "Notre équipe technique mobile intervient directement sur votre site pour des réparations immédiates.", s4: "Gestion de Flotte", s4d: "Services complets de suivi et d'optimisation pour les grandes flottes industrielles au Nigeria.", s5: "Certification Technique", s5d: "Inspection et certification officielles pour garantir la conformité aux normes industrielles nigérianes.", s6: "Support Terrain 24/7", s6d: "Assistance technique permanente pour les opérations critiques en mines, forage et construction.", ctaTitle: "Besoin d'un Support Immédiat?", ctaText: "Notre équipe de réponse technique est prête à aider avec vos besoins en machinerie dans tout le Nigeria.", ctaBtn: "Contacter l'Équipe Technique" },
  contact: { tagline: "Prendre Contact", title1: "Connectez-vous avec", title2: "Nos Experts.", hqTitle: "Siège Social", locLabel: "Adresse", locVal: "Complexe Industriel Garkuwan Kanam,\nVictoria Island, Lagos,\nRépublique Fédérale du Nigeria", callLabel: "Téléphone", emailLabel: "Email", hoursLabel: "Heures d'Ouverture", hoursVal: "Lun–Ven: 08h00 – 18h00\nSamedi: 09h00 – 14h00", urgentTitle: "Demande Urgente?", urgentText: "Nos spécialistes sont disponibles pour des consultations immédiates sur les acquisitions de flottes.", urgentLink: "Chat avec Ventes", formTitle: "Envoyer un Message", nameLbl: "Nom Complet", emailLbl: "Adresse Email", phoneLbl: "Numéro de Téléphone", subjectLbl: "Sujet", msgLbl: "Message", opt1: "Demande d'Équipement", opt2: "Support Technique", opt3: "Logistique & Livraison", opt4: "Partenariat", sendBtn: "Envoyer le Message", sending: "Envoi...", successTitle: "Message Envoyé!", successText: "Merci de nous avoir contactés. Notre équipe répondra dans les 24 heures ouvrables.", errorText: "Échec de l'envoi. Veuillez réessayer ou nous contacter directement via WhatsApp." },
  footer: { tagline: "La principale force du Nigeria en machines lourdes et équipements industriels. Nous comblons l'écart entre l'excellence technique mondiale et les besoins locaux.", navTitle: "Navigation", navHome: "Accueil", navInventory: "Catalogue", navServices: "Maintenance", navAbout: "Profil", navContact: "Contact", equipTitle: "Équipement", equipTrucks: "Camions Lourds", equipMining: "Solutions Minières", equipDrilling: "Systèmes de Forage", equipFeatured: "Stock en Vedette", hqTitle: "Siège Social", privacy: "Politique de Confidentialité", terms: "Conditions d'Utilisation" },
  common: { inStock: "En Stock", outOfStock: "Rupture de Stock", featured: "En Vedette", new_: "Neuf", used: "Occasion", refurbished: "Reconditionné" },
};

const es: T = {
  nav: { home: "Inicio", inventory: "Inventario", services: "Servicios", about: "Nosotros", contact: "Contacto", viewCatalog: "Ver Catálogo", language: "Idioma" },
  hero: { badge: "Garkuwan Kanam & Co Ventures", line1: "Construido para", line2: "Gran Escala.", line3: "Impulsado por", line4: "Potencia.", sub: "La principal puerta de Nigeria hacia maquinaria pesada de clase mundial. Desde la perforación profunda hasta operaciones mineras a gran escala, entregamos la fuerza que construye naciones.", cta1: "Explorar Inventario", cta2: "Chatear con Ventas" },
  stats: { units: "Unidades en Stock", trucks: "Camiones Pesados", mining: "Unidades Mineras", drilling: "Sistemas de Perforación" },
  featured: { label: "Selección Destacada", heading: "Stock Destacado", sub: "Maquinaria premium, inspeccionada y lista para despliegue inmediato en su sitio.", viewAll: "Inventario Completo", empty: "No hay artículos destacados ahora. Explore nuestro catálogo completo.", error: "No se pudieron cargar los productos destacados. Por favor intente de nuevo." },
  categories: { heading: "Explorar por Categoría", sub: "Encuentre el equipo adecuado para su operación", trucks: "Camiones Pesados", trucksDesc: "Transporte de carga larga distancia, volquetes y tractocamiones", mining: "Camiones Mineros", miningDesc: "Camiones de acarreo gigantes y dozers de cadenas para minería", drilling: "Motores de Perforación", drillingDesc: "Motores de fondo de pozo y sistemas de perforación direccional", browse: "Ver Todos" },
  why: { heading1: "El Socio Industrial", heading2: "de Confianza", sub: "Garkuwan Kanam & Co Ventures no es solo un proveedor. Somos una fuerza industrial que suministra maquinaria pesada verificada para los entornos más exigentes del continente.", v1: "Stock Verificado", v1d: "Cada unidad pasa una inspección industrial de 150 puntos antes de ser listada.", v2: "Alta Eficiencia", v2d: "Maquinaria optimizada para máximo tiempo de actividad y producción.", v3: "Marcas Certificadas", v3d: "Asociaciones directas con Caterpillar, FAW y Mercedes-Benz.", v4: "Alcance Regional", v4d: "Soporte logístico completo en los 36 estados de Nigeria y más allá." },
  cta: { heading: "¿Listo para Potenciar su Operación?", sub: "Consulte con nuestros expertos industriales hoy. Documentación técnica completa y soporte logístico para cada adquisición.", btn1: "WhatsApp Ventas", btn2: "Solicitar Cotización" },
  products: { pageTitle: "Catálogo Industrial", pageSub: "Cada unidad está certificada y lista para el campo. Filtre por categoría o busque modelos específicos.", all: "Todo el Equipo", trucks: "Camiones", mining: "Camiones Mineros", drilling: "Motores de Perforación", inStock: "Solo en Stock", search: "Buscar modelos...", sortName: "Ordenar: Nombre", sortAsc: "Precio: Menor–Mayor", sortDesc: "Precio: Mayor–Menor", showing: "Mostrando", results: "resultados", noResults: "Sin Coincidencias", noResultsDesc: "Intente ajustar sus filtros o términos de búsqueda.", reset: "Restablecer Filtros", error: "Error al Cargar Inventario", errorDesc: "No pudimos obtener la lista de equipos. Verifique su conexión.", retry: "Reintentar" },
  about: { tagline: "Nuestro Legado", title1: "Excelencia", title2: "Industrial.", sub: "Garkuwan Kanam & Co Ventures es un pilar de confiabilidad en el sector de equipos pesados de Nigeria, bridging global engineering and local demand.", missionTitle: "Nuestra Misión", missionText: "Empoderar el panorama industrial de Nigeria proporcionando acceso a maquinaria pesada verificada y de alto rendimiento que impulsa el crecimiento económico y el desarrollo de infraestructura.", visionTitle: "Nuestra Visión", visionText: "Ser la primera opción indiscutible para la adquisición de equipos pesados en África Occidental, reconocida por estándares inquebrantables de calidad e integridad profesional.", yearsExp: "Años de Experiencia", unitsDelivered: "Unidades Entregadas", valuesLabel: "Cómo Trabajamos", valuesTitle: "Nuestros Valores Fundamentales", val1: "Integridad", val1d: "Transparencia en cada transacción. Historial completo y verificación para cada equipo.", val2: "Calidad", val2d: "Solo almacenamos marcas líderes reconocidas por su durabilidad en entornos industriales exigentes.", val3: "Asociación", val3d: "Nuestra relación no termina en la entrega. Brindamos soporte continuo para mantenerlo operativo.", driveTitle: "Impulsando el Futuro de la Industria Nigeriana.", driveText: "Desde los campos petroleros del Delta hasta los sitios mineros del Norte, nuestro equipo es la columna vertebral de la industria nigeriana." },
  services: { tagline: "Soporte Industrial", title1: "Mantenimiento", title2: "& Soporte.", s1: "Mantenimiento Preventivo", s1d: "Servicio programado para garantizar que su maquinaria pesada opere a máximo rendimiento y evite costosas paradas.", s2: "Repuestos Genuinos", s2d: "Inventario completo de piezas OEM auténticas para Caterpillar, FAW, Mercedes-Benz e Iveco.", s3: "Reparaciones en Sitio", s3d: "Nuestro equipo técnico móvil se desplaza directamente a su sitio para reparaciones mecánicas y eléctricas.", s4: "Gestión de Flota", s4d: "Servicios completos de seguimiento y optimización para flotas industriales a gran escala en Nigeria.", s5: "Certificación Técnica", s5d: "Inspección y certificación oficial para garantizar el cumplimiento de todas las normas industriales nigerianas.", s6: "Soporte de Campo 24/7", s6d: "Asistencia técnica permanente para operaciones críticas en minería, perforación y construcción.", ctaTitle: "¿Necesita Soporte Inmediato?", ctaText: "Nuestro equipo de respuesta técnica está listo para ayudar con sus necesidades de maquinaria en toda Nigeria.", ctaBtn: "Contactar Equipo Técnico" },
  contact: { tagline: "Contacto", title1: "Conéctese con", title2: "Nuestros Expertos.", hqTitle: "Sede Central", locLabel: "Ubicación", locVal: "Complejo Industrial Garkuwan Kanam,\nVictoria Island, Lagos,\nRepública Federal de Nigeria", callLabel: "Llámenos", emailLabel: "Correo Electrónico", hoursLabel: "Horario Comercial", hoursVal: "Lun–Vie: 08:00 – 18:00\nSábado: 09:00 – 14:00", urgentTitle: "¿Consulta Urgente?", urgentText: "Nuestros especialistas en adquisiciones están disponibles para consultas inmediatas sobre flotas.", urgentLink: "Chat con Ventas", formTitle: "Enviar un Mensaje", nameLbl: "Nombre Completo", emailLbl: "Correo Electrónico", phoneLbl: "Número de Teléfono", subjectLbl: "Asunto", msgLbl: "Mensaje", opt1: "Consulta de Equipo", opt2: "Soporte Técnico", opt3: "Logística & Entrega", opt4: "Asociación", sendBtn: "Enviar Mensaje", sending: "Enviando...", successTitle: "¡Mensaje Enviado!", successText: "Gracias por contactarnos. Nuestro equipo responderá en 24 horas hábiles.", errorText: "Error al enviar el mensaje. Intente de nuevo o contáctenos por WhatsApp." },
  footer: { tagline: "La principal fuerza de Nigeria en maquinaria pesada y equipos industriales. Conectamos la excelencia técnica global con las necesidades industriales locales.", navTitle: "Navegación", navHome: "Inicio", navInventory: "Catálogo", navServices: "Mantenimiento", navAbout: "Perfil", navContact: "Contacto", equipTitle: "Equipo", equipTrucks: "Camiones Pesados", equipMining: "Soluciones Mineras", equipDrilling: "Sistemas de Perforación", equipFeatured: "Stock Destacado", hqTitle: "Sede Central", privacy: "Política de Privacidad", terms: "Términos de Servicio" },
  common: { inStock: "En Stock", outOfStock: "Agotado", featured: "Destacado", new_: "Nuevo", used: "Usado", refurbished: "Reacondicionado" },
};

const ar: T = {
  nav: { home: "الرئيسية", inventory: "المخزون", services: "الخدمات", about: "من نحن", contact: "اتصل بنا", viewCatalog: "عرض الكتالوج", language: "اللغة" },
  hero: { badge: "Garkuwan Kanam & Co Ventures", line1: "مبني من أجل", line2: "الحجم الكبير.", line3: "مدفوع بـ", line4: "القوة.", sub: "البوابة الرائدة في نيجيريا للآلات الثقيلة عالمية المستوى. من الحفر العميق إلى عمليات التعدين الكبرى، نوفر القوة التي تبني الأمم.", cta1: "استعرض المخزون", cta2: "تحدث مع المبيعات" },
  stats: { units: "وحدات في المخزون", trucks: "شاحنات ثقيلة", mining: "وحدات التعدين", drilling: "أنظمة الحفر" },
  featured: { label: "اختيار مميز", heading: "المخزون المميز", sub: "آلات فاخرة، تم فحصها وجاهزة للنشر الفوري في موقعك.", viewAll: "المخزون الكامل", empty: "لا توجد منتجات مميزة حالياً. تصفح الكتالوج الكامل.", error: "تعذر تحميل المنتجات المميزة. يرجى المحاولة مرة أخرى." },
  categories: { heading: "تصفح حسب الفئة", sub: "ابحث عن المعدات المناسبة لعمليتك", trucks: "شاحنات ثقيلة", trucksDesc: "نقل بضائع طويل المدى، قلابات ووحدات جرار للنقل الطرقي", mining: "شاحنات تعدين", miningDesc: "شاحنات نقل ضخمة وجرافات زاحفة لعمليات التعدين", drilling: "محركات الحفر", drillingDesc: "محركات الطين تحت الأرض وأنظمة الحفر الاتجاهي", browse: "تصفح الكل" },
  why: { heading1: "الشريك الصناعي", heading2: "الموثوق", sub: "Garkuwan Kanam & Co Ventures ليست مجرد مورد. نحن قوة صناعية توفر آلات ثقيلة موثقة للبيئات الأكثر تطلباً في القارة.", v1: "مخزون موثق", v1d: "كل وحدة تخضع لفحص صناعي من 150 نقطة قبل الإدراج.", v2: "كفاءة عالية", v2d: "آلات محسّنة لأقصى وقت تشغيل وإنتاجية.", v3: "علامات تجارية معتمدة", v3d: "شراكات مباشرة مع Caterpillar وFAW وMercedes-Benz.", v4: "نطاق إقليمي", v4d: "دعم لوجستي كامل في جميع ولايات نيجيريا الـ36 وما بعدها." },
  cta: { heading: "مستعد لتعزيز عملياتك؟", sub: "استشر خبراءنا الصناعيين اليوم. توثيق تقني كامل ودعم لوجستي لكل عملية استحواذ.", btn1: "واتساب المبيعات", btn2: "طلب عرض سعر" },
  products: { pageTitle: "الكتالوج الصناعي", pageSub: "كل وحدة معتمدة صناعياً وجاهزة للميدان. صفِّ حسب الفئة أو ابحث عن طرازات محددة.", all: "كل المعدات", trucks: "الشاحنات", mining: "شاحنات التعدين", drilling: "محركات الحفر", inStock: "المتوفر فقط", search: "البحث عن الطرازات...", sortName: "ترتيب: الاسم", sortAsc: "السعر: من الأقل", sortDesc: "السعر: من الأعلى", showing: "عرض", results: "نتائج", noResults: "لا توجد معدات مطابقة", noResultsDesc: "حاول تعديل الفلاتر أو مصطلحات البحث.", reset: "إعادة ضبط الفلاتر", error: "فشل تحميل المخزون", errorDesc: "تعذر جلب قائمة المعدات. تحقق من اتصالك.", retry: "إعادة المحاولة" },
  about: { tagline: "إرثنا", title1: "التميز", title2: "الصناعي.", sub: "تقف Garkuwan Kanam & Co Ventures كركيزة موثوقية في قطاع المعدات الثقيلة في نيجيريا، تجسر الهوة بين الهندسة العالمية والطلب الصناعي المحلي.", missionTitle: "مهمتنا", missionText: "تمكين المشهد الصناعي في نيجيريا من خلال توفير الوصول إلى آلات ثقيلة موثقة وعالية الأداء تدفع النمو الاقتصادي وتطوير البنية التحتية.", visionTitle: "رؤيتنا", visionText: "أن نكون الخيار الأول الذي لا جدال فيه للحصول على المعدات الثقيلة في غرب أفريقيا، معروفين بمعايير جودة ونزاهة مهنية لا تتنازل.", yearsExp: "سنوات الخبرة", unitsDelivered: "وحدات تم توصيلها", valuesLabel: "كيف نعمل", valuesTitle: "قيمنا الأساسية", val1: "النزاهة", val1d: "الشفافية في كل معاملة. تاريخ كامل وتحقق لكل قطعة معدات نبيعها.", val2: "الجودة", val2d: "نخزن فقط العلامات التجارية الرائدة المعروفة بمتانتها في البيئات الصناعية القاسية.", val3: "الشراكة", val3d: "علاقتنا لا تنتهي عند التسليم. نقدم دعماً تقنياً مستمراً للحفاظ على تشغيلك.", driveTitle: "ندفع مستقبل الصناعة النيجيرية.", driveText: "من حقول النفط في الدلتا إلى مواقع التعدين في الشمال، معداتنا هي العمود الفقري للصناعة النيجيرية." },
  services: { tagline: "الدعم الصناعي", title1: "الصيانة", title2: "والدعم.", s1: "الصيانة الوقائية", s1d: "خدمة منتظمة لضمان تشغيل آلاتك الثقيلة بأداء أمثل وتجنب التوقف المكلف.", s2: "قطع غيار أصلية", s2d: "مخزون شامل من قطع OEM الأصلية لـ Caterpillar وFAW وMercedes-Benz وIveco.", s3: "إصلاح في الموقع", s3d: "ينتشر فريقنا التقني المتنقل مباشرة في موقعك للإصلاحات الميكانيكية والكهربائية الفورية.", s4: "إدارة الأسطول", s4d: "خدمات تتبع وتحسين شاملة للأساطيل الصناعية واسعة النطاق في جميع أنحاء نيجيريا.", s5: "الشهادة التقنية", s5d: "فحص وإصدار شهادات رسمية لضمان امتثال معداتك لجميع المعايير الصناعية النيجيرية.", s6: "دعم ميداني 24/7", s6d: "مساعدة تقنية على مدار الساعة للعمليات الحيوية في قطاعات التعدين والحفر والبناء.", ctaTitle: "تحتاج دعماً فورياً؟", ctaText: "فريق الاستجابة التقنية لدينا في انتظار مساعدتك في احتياجات الآلات الخاصة بك.", ctaBtn: "اتصل بالفريق التقني" },
  contact: { tagline: "تواصل معنا", title1: "تواصل مع", title2: "خبرائنا.", hqTitle: "المقر الرئيسي", locLabel: "الموقع", locVal: "مجمع Garkuwan Kanam الصناعي،\nجزيرة فيكتوريا، لاغوس،\nجمهورية نيجيريا الاتحادية", callLabel: "اتصل بنا", emailLabel: "البريد الإلكتروني", hoursLabel: "ساعات العمل", hoursVal: "الاثنين–الجمعة: 08:00 – 18:00\nالسبت: 09:00 – 14:00", urgentTitle: "استفسار عاجل؟", urgentText: "متخصصو المشتريات لدينا متاحون للتشاور الفوري حول اقتناءات الأسطول الكبير.", urgentLink: "تحدث مع المبيعات", formTitle: "إرسال رسالة", nameLbl: "الاسم الكامل", emailLbl: "البريد الإلكتروني", phoneLbl: "رقم الهاتف", subjectLbl: "الموضوع", msgLbl: "الرسالة", opt1: "استفسار عن معدات", opt2: "الدعم التقني", opt3: "اللوجستيات والتسليم", opt4: "الشراكة", sendBtn: "إرسال الرسالة", sending: "جارٍ الإرسال...", successTitle: "تم إرسال الرسالة!", successText: "شكراً لتواصلك معنا. سيرد فريقنا خلال 24 ساعة عمل.", errorText: "فشل إرسال الرسالة. يرجى المحاولة مرة أخرى أو التواصل عبر واتساب." },
  footer: { tagline: "القوة الرائدة في نيجيريا في مجال الآلات الثقيلة والمعدات الصناعية. نجسر الهوة بين التميز الهندسي العالمي والاحتياجات الصناعية المحلية.", navTitle: "التنقل", navHome: "الرئيسية", navInventory: "الكتالوج", navServices: "الصيانة", navAbout: "الملف", navContact: "اتصل بنا", equipTitle: "المعدات", equipTrucks: "الشاحنات الثقيلة", equipMining: "حلول التعدين", equipDrilling: "أنظمة الحفر", equipFeatured: "المخزون المميز", hqTitle: "المقر الرئيسي", privacy: "سياسة الخصوصية", terms: "شروط الخدمة" },
  common: { inStock: "في المخزون", outOfStock: "نفد من المخزون", featured: "مميز", new_: "جديد", used: "مستعمل", refurbished: "مجدد" },
};

const zh: T = {
  nav: { home: "首页", inventory: "库存", services: "服务", about: "关于我们", contact: "联系我们", viewCatalog: "查看目录", language: "语言" },
  hero: { badge: "Garkuwan Kanam & Co Ventures", line1: "专为", line2: "规模而建。", line3: "由", line4: "动力驱动。", sub: "尼日利亚通向世界级重型机械的首要门户。从深井钻探到大规模采矿作业，我们提供建设国家的力量。", cta1: "浏览库存", cta2: "联系销售" },
  stats: { units: "库存单位", trucks: "重型卡车", mining: "矿用单位", drilling: "钻探系统" },
  featured: { label: "精选产品", heading: "精选库存", sub: "优质机械，经过检验，可立即部署至您的工地。", viewAll: "完整库存", empty: "暂无精选产品。请浏览完整目录。", error: "无法加载精选产品，请重试。" },
  categories: { heading: "按类别浏览", sub: "为您的作业找到合适的设备", trucks: "重型卡车", trucksDesc: "长途货运、自卸车及牵引单元", mining: "矿用卡车", miningDesc: "大型矿用自卸车及履带式推土机", drilling: "钻探电机", drillingDesc: "井下泥浆马达及定向钻探系统", browse: "浏览全部" },
  why: { heading1: "值得信赖的", heading2: "工业合作伙伴", sub: "Garkuwan Kanam & Co Ventures不仅仅是供应商。我们是一股工业力量，为非洲大陆最苛刻的环境提供经过验证的重型机械。", v1: "经验证库存", v1d: "每台设备上架前均经过150点工业检验。", v2: "高效能", v2d: "优化的机械设备，实现最大运行时间和产量。", v3: "认证品牌", v3d: "与卡特彼勒、一汽和奔驰建立直接合作关系。", v4: "区域覆盖", v4d: "在尼日利亚36个州及以外提供完整物流支持。" },
  cta: { heading: "准备好为您的运营提供动力？", sub: "立即咨询我们的工业专家。为每次采购提供完整的技术文档和后勤支持。", btn1: "WhatsApp销售", btn2: "申请报价" },
  products: { pageTitle: "工业目录", pageSub: "每台设备均经过行业认证，现场就绪。按类别筛选或搜索特定型号。", all: "所有设备", trucks: "卡车", mining: "矿用卡车", drilling: "钻探电机", inStock: "仅显示有货", search: "搜索型号...", sortName: "排序：名称", sortAsc: "价格：低到高", sortDesc: "价格：高到低", showing: "显示", results: "条结果", noResults: "无匹配设备", noResultsDesc: "请尝试调整筛选条件或搜索关键词。", reset: "重置筛选", error: "加载库存失败", errorDesc: "无法获取设备列表，请检查网络连接。", retry: "重试" },
  about: { tagline: "我们的传承", title1: "工业", title2: "卓越。", sub: "Garkuwan Kanam & Co Ventures是尼日利亚重型设备领域可靠性的支柱，弥合全球工程卓越与本地工业需求之间的差距。", missionTitle: "我们的使命", missionText: "通过提供高性能、经验证的重型机械，赋能尼日利亚工业格局，推动整个西非的经济增长和基础设施发展。", visionTitle: "我们的愿景", visionText: "成为西非重型设备采购的无可争议首选，以不妥协的质量标准、职业诚信和技术专长著称。", yearsExp: "年经验", unitsDelivered: "交付单位", valuesLabel: "我们的方式", valuesTitle: "核心价值观", val1: "诚信", val1d: "每笔交易透明公开。为每件销售设备提供完整历史记录和验证。", val2: "质量", val2d: "我们仅备货在恶劣工业环境中以耐用性著称的行业领先品牌。", val3: "合作", val3d: "我们的关系不止于交付。我们提供持续技术支持，确保您的设备保持运营。", driveTitle: "推动尼日利亚工业的未来。", driveText: "从三角洲的油田到北部的矿山，我们的设备是尼日利亚工业的支柱，是该国最重要基础设施项目背后的无声力量。" },
  services: { tagline: "工业支持", title1: "维护", title2: "与支持。", s1: "预防性维护", s1d: "定期保养，确保您的重型机械以最佳性能运行，避免高成本停机。", s2: "正品备件", s2d: "卡特彼勒、一汽、奔驰和依维柯设备的全系列OEM原厂备件库存。", s3: "现场维修", s3d: "我们的移动技术团队直接部署到您的现场，进行即时机械和电气维修。", s4: "车队管理", s4d: "为尼日利亚各地大规模工业车队提供全面跟踪和优化服务。", s5: "技术认证", s5d: "官方检验和认证，确保您的设备符合所有尼日利亚工业监管标准。", s6: "7×24小时现场支持", s6d: "为采矿、钻探和建筑领域关键作业提供全天候技术援助。", ctaTitle: "需要即时支持？", ctaText: "我们的技术响应团队随时准备协助您在尼日利亚各地的机械需求。", ctaBtn: "联系技术团队" },
  contact: { tagline: "联系我们", title1: "与我们的", title2: "专家联系。", hqTitle: "总部", locLabel: "位置", locVal: "Garkuwan Kanam工业园区，\n维多利亚岛，拉各斯，\n尼日利亚联邦共和国", callLabel: "致电我们", emailLabel: "电子邮件", hoursLabel: "营业时间", hoursVal: "周一至周五：08:00 – 18:00\n周六：09:00 – 14:00", urgentTitle: "紧急咨询？", urgentText: "我们的采购专家可随时就大规模车队采购进行即时咨询。", urgentLink: "联系销售", formTitle: "发送消息", nameLbl: "全名", emailLbl: "电子邮件地址", phoneLbl: "电话号码", subjectLbl: "主题", msgLbl: "消息", opt1: "设备咨询", opt2: "技术支持", opt3: "物流与配送", opt4: "合作", sendBtn: "发送消息", sending: "发送中...", successTitle: "消息已发送！", successText: "感谢您的联系。我们的团队将在24个工作小时内回复。", errorText: "发送消息失败。请重试或通过WhatsApp直接联系我们。" },
  footer: { tagline: "尼日利亚重型机械和工业设备领域的首要力量。弥合全球工程卓越与本地工业需求之间的差距。", navTitle: "导航", navHome: "首页", navInventory: "目录", navServices: "维护", navAbout: "简介", navContact: "联系", equipTitle: "设备", equipTrucks: "重型卡车", equipMining: "采矿解决方案", equipDrilling: "钻探系统", equipFeatured: "精选库存", hqTitle: "总部", privacy: "隐私政策", terms: "服务条款" },
  common: { inStock: "有货", outOfStock: "缺货", featured: "精选", new_: "全新", used: "二手", refurbished: "翻新" },
};

const translations: Record<LangCode, T> = { en, fr, es, ar, zh };

interface LangCtx { lang: LangCode; setLang: (l: LangCode) => void; t: T; }
const LanguageContext = createContext<LangCtx>({ lang: "en", setLang: () => {}, t: en });

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const stored = typeof localStorage !== "undefined" ? (localStorage.getItem(LANG_KEY) as LangCode | null) : null;
  const valid: LangCode[] = ["en", "fr", "es", "ar", "zh"];
  const initial: LangCode = stored && valid.includes(stored as LangCode) ? (stored as LangCode) : "en";
  const [lang, setLangState] = useState<LangCode>(initial);
  const setLang = (l: LangCode) => { setLangState(l); localStorage.setItem(LANG_KEY, l); };
  return <LanguageContext.Provider value={{ lang, setLang, t: translations[lang] }}>{children}</LanguageContext.Provider>;
}

export function useLanguage() { return useContext(LanguageContext); }

export const LANGUAGES: { code: LangCode; nativeName: string; flag: string }[] = [
  { code: "en", nativeName: "English",  flag: "🇬🇧" },
  { code: "fr", nativeName: "Français", flag: "🇫🇷" },
  { code: "es", nativeName: "Español",  flag: "🇪🇸" },
  { code: "ar", nativeName: "العربية", flag: "🇸🇦" },
  { code: "zh", nativeName: "中文",     flag: "🇨🇳" },
];
